spring:
  config:
    import: application-secret.yml
    activate:
      on-profile: local
  data:
    redis:
      host: localhost
      port: 6379
      repositories:
        enabled: false
  application:
    name: api-gateway
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"  # 프론트엔드 개발 서버
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: '*'
            allowCredentials: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: member-service
          uri: lb://member-service
          predicates:
            - Path=/api/members/**


jwt:
  secret : ${JWT_SECRET}
  expiration: 3600000 # 1 hour in milliseconds
  refresh-token-expiration: 604800000 # 7 days in milliseconds

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30  # 갱신 주기 설정 (기본값은 30초)

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic




public:
  paths:
    - /public/
    - /api/auth/login
    - /api/members/register
    - /api/members/activate