server:
    port: 8080

spring:
  application:
    name : api-gateway
  main:
    allow-bean-definition-overriding: true
  cloud:
    compatibility-verifier:
      enable: false
  data:
    redis:
      host: localhost
      port: 6379
      repositories:
        enabled: false


jwt:
  expiration: 3600000 # 1 hour in milliseconds
  secret: bf42ac7953a2f1d5479abc2ad8fc7510c627c88011251fd12b861d18e2059bfe74989766f77a4e4427fd621ca95c3c02a2b252090d517d5cb568ceb1a809a769
  refresh-token-expiration: 604800000 # 7 days in milliseconds

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

