server:
  port: 8080

#Eureka 설정
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30  # 갱신 주기 설정 (기본값은 30초)

spring:
  config:
    import : application-secret.yml
    activate:
      on-profile: docker
  application:
    name: api-gateway


  # Cloud Gateway 설정
  cloud:
    gateway:
      routes :
        - id : member-service
          uri : lb://member-service
          predicates:
            - Path=/api/members/**,/api/auth/**,/api/profile/**
          filters:
            - StripPrefix=1
            - name : JwtAuthFilter
              args :
                publicPaths:
                - "/auth/login"
                - "/members/register"
                - "/members/activate"
        - id: refresh-token
          uri: lb://member-service
          predicates:
            - Path=/api/auth/refresh
          filters:
            - StripPrefix=1
            - name: AccessTokenFilter

      default-filters:
        - name : GlobalFilter
          args :
            baseMessage: "Spring Cloud Gateway Global Filter"
            preLogger: true
            postLogger: true

  data:
    redis:
      host: redis
      port: 6379
      repositories:
        enabled: false
      password: 1234

jwt:
  secret : ${JWT_SECRET}


