server :
    port : 8082

spring:
  application:
    name : stock-service
    config:
      activate:
        on-profile: docker

  jpa :
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
      database-platform: org.hibernate.dialect.MySQL8Dialect
    datasource:
      url: jdbc:mysql://mysql:3306/stocktalk
      username: root
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:29092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  data:
    redis:
      host: redis
      port: 6379
      repositories:
        enabled: false
      password: 1234


eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true



logging:
  level:
    org.springframework.data.redis: DEBUG
    org.springframework.boot.autoconfigure.data.redis: DEBUG