server:
  port: 8081

spring:
  application:
    name: member-service
  config:
    import: application-secret.yml
    activate:
      on-profile: dev

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:29092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://mysql:3306/stocktalk
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: redis
      port: 6379
      repositories:
        enabled: false
      password: 1234

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true

app:
  activation-base-url: http://localhost:8080/api/members/activate?token=

auth-code-expiration-millis: 1800000  # 30분

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000  # 1시간(밀리초 단위)




logging:
  level:
    org.springframework.data.redis: DEBUG
    org.springframework.boot.autoconfigure.data.redis: DEBUG